### ISSUE TITLE
Patreon extension returning 403

### ISSUE THREAD

**Issue by mr-tchoo** [ysh16/newsboat-extensions#1]
I have just tried using your Patreon extension but the request to the campaign endpoint returns 403.

Does it still work for you and how so?

**Comment by ysh16** [comment]
Yes, it is still working.
I suspect you were passing it an argument other than the Patreon creator's username.
i.e. https://www.patreon.com/GiftedHater/posts -> `/path/to/newsboat-extensions/patreon2rss.py GiftedHater`

Sorry for the late response.
